version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moneymanager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
        - "3307:3306"